package org.see.mao.persistence;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Is used to specify the mapped column for a persistent property or field.
 */
@Target(FIELD)
@Retention(RUNTIME)
public @interface Column {

	/**
	 * (Optional) The name of the column. Defaults to the property or field
	 * name.
	 */
	String name() default "";

	/**
	 * (Optional) Whether the database column is queryable.
	 */
	boolean queryable() default true;

	/**
	 * (Optional) Whether the column is included in SQL INSERT statements
	 * generated by the persistence provider.
	 */
	boolean insertable() default true;

	/**
	 * (Optional) Whether the column is included in SQL UPDATE statements
	 * generated by the persistence provider.
	 */
	boolean updatable() default true;

	/**
	 * (Optional) The column length. (Applies only if a string-valued column is
	 * used.)
	 */
	int length() default 255;
}
